// Generated by CoffeeScript 1.6.1

Package.describe({
  summary: 'A pattern to display application errors to the user'
});

Package.on_use(function (api, where) {
  api.use(['coffeescript', 'minimongo', 'mongo-livedata', 'templating'], 'client');

  api.add_files(['errors.coffee', 'errors_list.html', 'errors_list.coffee'], 'client');
});
